Repository woorifisa-service-dev-4th/frontend-1st-dding-ho-wa, pull requests merged in 2025-01, with the labels that each got.

#5 feat: 공통 레이아웃 작업
  img/background.svg
  img/bag.svg
  img/bagTop.svg
  index.css
  index.html
Labels: feat

#7 Feat: 홈화면 구현완료
  audio/homeBGM.mp3
  img/bagTop.svg
  img/home/left_dragon.svg
  img/home/left_light.svg
  img/home/right.svg
  index.css
  index.html
Labels: feat

#9 feat: 게임 화면 뷰 작업 및 홈화면과 결과 화면 통합
  audio/quizBGM.mp3
  data/android.png
  data/angular.png
  data/chinese_new_year.mp3
  data/css.png
  data/docker.png
  data/firebase.png
  data/git.png
  data/github.png
  data/html.png
  data/java.png
  data/js.png
  data/kotlin.png
  data/linux.png
  data/mariaDB.png
  data/mysql.png
  data/nodejs.png
  data/python.png
  data/react.png
  data/ruby.png
  data/svelte.png
  data/swift.png
  data/typescript.png
  data/ubuntu.png
  data/vscode.png
  data/vue.png
  game.css
  game.html
  game2.css
  game2.html
  img/bag.svg
  img/favicon.png
  index.css
  index.html
  result.css
  result.html
Labels: feat

#12 feat: 해상도 별 반응형 작업
  game.css
  game.html
  game2.css
  game2.html
  index.css
  index.html
Labels: feat

#14 feat: 성능 최적화 작업(메타 태그 설정, 이미지 포맷 최적화 등)
  data/chinese_new_year.mp3
  data/css.webp
  data/python.webp
  game.css
  game.html
  game2.css
  game2.html
  img/background.webp
  img/bagTop.webp
  img/home/right.webp
  index.css
  index.html
  result.css
Labels: feat

#19 chore: setting eslint, prettier
  .eslintrc.json
  .prettierrc.json
  package-lock.json
  package.json
Labels: chore

#23 feat: node 기초 세팅
  README.md
  data/android.png
  data/angular.png
  data/css.png
  data/css.webp
  data/docker.png
  data/firebase.png
  data/git.png
  data/github.png
  data/html.png
  data/java.png
  data/js.png
  data/kotlin.png
  data/linux.png
  data/mariaDB.png
  data/mysql.png
  data/nodejs.png
  data/python.png
  data/python.webp
  data/react.png
  data/ruby.png
  data/svelte.png
  data/swift.png
  data/typescript.png
  data/ubuntu.png
  data/vscode.png
  data/vue.png
  index.html
  public/audio/homeBGM.mp3
  public/audio/quizBGM.mp3
  public/font/YoonDokrip.otf
  public/game.css
  public/game.html
  public/img/background.svg
  public/img/background.webp
  public/img/bag.svg
  public/img/bagTop.svg
  public/img/bagTop.webp
  public/img/favicon.png
  public/img/home/left_dragon.svg
  public/img/home/left_light.svg
  public/img/home/right.svg
  public/img/home/right.webp
  public/img/result/img_background_result.svg
  public/img/result/img_bag_result.svg
  public/index.css
  public/index.html
  server.js
Labels: feat

#26 feat: 결과값 받아오는 post, 랭킹 데이터 get api 작업 및 db 연동 작업
  .eslintrc.json
  package-lock.json
  package.json
  server.js
Labels: feat

#29 Feat/#27 정답, 오답 처리 모달 제작
  game.js
  public/game.css
  public/game.html
  public/img/bell.png
Labels: feat

#31 fix : modal 함수 오타 수정
  game.js
Labels: feat

#32 Feat/#21 game implement
  public/api/api.js
  public/game.css
  public/game.html
  public/game.js
  public/img/라멘.png
  public/img/짜장면.png
  public/img/짬뽕.png
  public/index.html
  public/index.js
  public/timer.css
  public/timer.js
  server.js
  timer.css
  timer.html
Labels: feat

#39 Feat: 버튼 공통 컴포넌트화 구현 완료
  src/components/Button/Button.jsx
  src/components/Button/Button.style.js
Labels: :sparkles: feat

#40 Feat/#36 feat react modal
  legacy/index.css
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.js
  src/pages/Home.jsx
Labels: :sparkles: feat

#43 refactor: modal onClick 수정
  src/App.jsx
  src/components/Modal/Modal.jsx
  src/pages/Result.jsx
  src/pages/Result/Result.css
  src/pages/Result/Result.jsx
  src/pages/Result/Result.style.js
Labels: :sparkles: feat

#45 Refactor: 홈 화면 리팩토링
  legacy/index.css
  legacy/index.html
  src/App.jsx
  src/components/Button/Button.style.js
  src/components/GlobalStyle/GlobalStyle.style.js
  src/components/Home/CenterBody.jsx
  src/components/Home/CenterBody.style.js
  src/components/Home/HomeBody.jsx
  src/components/Home/HomeLayout.style.js
  src/components/Home/LeftBody.jsx
  src/components/Home/LeftBody.style.js
  src/components/Home/ModalContent.jsx
  src/components/Home/ModalContent.style.js
  src/components/Home/RightBody.jsx
  src/components/Home/RightBody.style.js
  src/pages/Home.jsx
Labels: :sparkles: feat

#47 Feat/#46 랭킹 조회 api
  server.js
  src/apis/getResult.js
  src/pages/Result/Result.jsx
Labels: :sparkles: feat

#49 rename: 홈 컴포넌트 디렉터리 이동
  src/App.jsx
  src/components/CenterBody/CenterBody.jsx
  src/components/CenterBody/CenterBody.style.js
  src/components/HomeBody/HomeBody.jsx
  src/components/HomeLayout/HomeLayout.style.js
  src/components/LeftBody/LeftBody.jsx
  src/components/LeftBody/LeftBody.style.js
  src/components/ModalContent/ModalContent.jsx
  src/components/ModalContent/ModalContent.style.js
  src/components/RightBody/RightBody.jsx
  src/components/RightBody/RightBody.style.js
  src/pages/Home/Home.jsx
Labels: :recycle: refactor
